# -*- coding: utf-8 -*-
"""41. Area and Perimeter .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WiDYeLyTlGFOXWKxyoAuLRFkOuyPYapL
"""

class rectangle:
    def __init__(self,length,width):

        self.length = length
        self.width = width

    def area(self):

        return self.length * self.width
    def perimeter (self):

        return 2*(self.length + self.width)
  #example usage
rectangle = rectangle(4,8)
print("area:", rectangle.area())
print("perimeter:",rectangle.perimeter())